######################################################################
# Automatically generated by qmake (2.00a) ven 24. giu 14:14:20 2005
######################################################################

TARGET = test_hash2d
DEPENDPATH += . 
INCLUDEPATH += . ../../..
CONFIG += console stl
TEMPLATE = app
HEADERS += ../../../vcg/space/index/grid_static_ptr2d.h\
           ../../../vcg/space/index/closest2d.h\
           ../../../vcg/space/index/space_iterators2d.h\
           ../../../vcg/space/index/grid_closest2d.h

SOURCES += test_hash2d.cpp
