######################################################################
# Automatically generated by qmake (2.00a) ven 24. giu 14:14:20 2005
######################################################################

TARGET = trimesh_join
DEPENDPATH += . 
INCLUDEPATH += . ../../..
CONFIG += console stl
TEMPLATE = app
HEADERS += ../../../vcg/space/index/index2D/spatial_hashing_2D.h

SOURCES += test_hash2D.cpp
