######################################################################
# Automatically generated by qmake (2.00a) ven 24. giu 14:14:20 2005
######################################################################

TARGET = test_hash2d
DEPENDPATH += . 
INCLUDEPATH += . ../../..
CONFIG += console stl
TEMPLATE = app
HEADERS += ../../../vcg/space/index/index2d/grid_static_ptr_2d.h\
           ../../../vcg/space/index/index2d/closest_2d.h\
           ../../../vcg/space/index/index2d/space_iterators_2d.h\
           ../../../vcg/space/index/index2d/grid_closest_2d.h

SOURCES += test_hash2d.cpp
