######################################################################
# Automatically generated by qmake (2.00a) ven 24. giu 14:14:20 2005
######################################################################

TARGET = trimesh_join
DEPENDPATH += . 
INCLUDEPATH += . ../../..
CONFIG += console stl
TEMPLATE = app
HEADERS += ../../../vcg/space/index/index2D/grid_static_ptr_2D.h\
           ../../../vcg/space/index/index2D/closest_2D.h\
           ../../../vcg/space/index/index2D/space_iterators_2D.h\
           ../../../vcg/space/index/index2D/grid_closest_2D.h

SOURCES += test_hash2D.cpp
