######################################################################
# Automatically generated by qmake (2.00a) ven 24. giu 14:14:20 2005
######################################################################

TARGET = trimesh_join
LIBPATH += 
DEPENDPATH += . 
INCLUDEPATH += . ../../..
CONFIG += console stl
TEMPLATE = app
HEADERS += ../../../vcg/complex/trimesh/subset.h

SOURCES += trimesh_join.cpp ../../../wrap/ply/plylib.cpp