var searchData=
[
  ['centerpointbarycenter_0',['CenterPointBarycenter',['../structvcg_1_1tri_1_1CenterPointBarycenter.html',1,'vcg::tri']]],
  ['clean_1',['Clean',['../classvcg_1_1tri_1_1Clean.html',1,'vcg::tri']]],
  ['color_2',['Color',['../classvcg_1_1edge_1_1Color.html',1,'vcg::edge::Color&lt; A, T &gt;'],['../classvcg_1_1face_1_1Color.html',1,'vcg::face::Color&lt; A, T &gt;'],['../classvcg_1_1vertex_1_1Color.html',1,'vcg::vertex::Color&lt; A, T &gt;']]],
  ['color4_3',['Color4',['../classvcg_1_1Color4.html',1,'vcg']]],
  ['color4b_4',['Color4b',['../classvcg_1_1edge_1_1Color4b.html',1,'vcg::edge::Color4b&lt; TT &gt;'],['../classvcg_1_1face_1_1Color4b.html',1,'vcg::face::Color4b&lt; T &gt;'],['../classvcg_1_1vertex_1_1Color4b.html',1,'vcg::vertex::Color4b&lt; TT &gt;']]],
  ['color_3c_20vcg_3a_3acolor4b_2c_20t_20_3e_5',['Color&lt; vcg::Color4b, T &gt;',['../classvcg_1_1face_1_1Color.html',1,'vcg::face']]],
  ['color_3c_20vcg_3a_3acolor4b_2c_20tt_20_3e_6',['Color&lt; vcg::Color4b, TT &gt;',['../classvcg_1_1edge_1_1Color.html',1,'vcg::edge']]],
  ['coloravginfo_7',['ColorAvgInfo',['../classvcg_1_1tri_1_1UpdateColor_1_1ColorAvgInfo.html',1,'vcg::tri::UpdateColor']]],
  ['com_8',['CoM',['../classvcg_1_1tri_1_1CoM.html',1,'vcg::tri']]],
  ['comembed_9',['CoMEmbed',['../classvcg_1_1tri_1_1CoMEmbed.html',1,'vcg::tri']]],
  ['compareareafp_10',['CompareAreaFP',['../structvcg_1_1tri_1_1Clean_1_1CompareAreaFP.html',1,'vcg::tri::Clean']]],
  ['connectedcomponentiterator_11',['ConnectedComponentIterator',['../classvcg_1_1tri_1_1ConnectedComponentIterator.html',1,'vcg::tri']]],
  ['coord_12',['Coord',['../classvcg_1_1vertex_1_1Coord.html',1,'vcg::vertex']]],
  ['coord3d_13',['Coord3d',['../classvcg_1_1vertex_1_1Coord3d.html',1,'vcg::vertex']]],
  ['coord3f_14',['Coord3f',['../classvcg_1_1vertex_1_1Coord3f.html',1,'vcg::vertex']]],
  ['coord_3c_20vcg_3a_3apoint3d_2c_20t_20_3e_15',['Coord&lt; vcg::Point3d, T &gt;',['../classvcg_1_1vertex_1_1Coord.html',1,'vcg::vertex']]],
  ['coord_3c_20vcg_3a_3apoint3f_2c_20t_20_3e_16',['Coord&lt; vcg::Point3f, T &gt;',['../classvcg_1_1vertex_1_1Coord.html',1,'vcg::vertex']]],
  ['curvaturedir_17',['CurvatureDir',['../classvcg_1_1face_1_1CurvatureDir.html',1,'vcg::face::CurvatureDir&lt; A, TT &gt;'],['../classvcg_1_1vertex_1_1CurvatureDir.html',1,'vcg::vertex::CurvatureDir&lt; A, TT &gt;']]],
  ['curvaturedir_3c_20curvaturedirbasetype_3c_20double_20_3e_2c_20t_20_3e_18',['CurvatureDir&lt; CurvatureDirBaseType&lt; double &gt;, T &gt;',['../classvcg_1_1face_1_1CurvatureDir.html',1,'vcg::face']]],
  ['curvaturedir_3c_20curvaturedirbasetype_3c_20float_20_3e_2c_20t_20_3e_19',['CurvatureDir&lt; CurvatureDirBaseType&lt; float &gt;, T &gt;',['../classvcg_1_1face_1_1CurvatureDir.html',1,'vcg::face']]],
  ['curvaturedirbasetype_20',['CurvatureDirBaseType',['../structvcg_1_1face_1_1CurvatureDirBaseType.html',1,'vcg::face::CurvatureDirBaseType&lt; S &gt;'],['../structvcg_1_1vertex_1_1CurvatureDirBaseType.html',1,'vcg::vertex::CurvatureDirBaseType&lt; S &gt;']]],
  ['curvaturedirbasetype_3c_20double_20_3e_21',['CurvatureDirBaseType&lt; double &gt;',['../structvcg_1_1face_1_1CurvatureDirBaseType.html',1,'vcg::face']]],
  ['curvaturedirbasetype_3c_20float_20_3e_22',['CurvatureDirBaseType&lt; float &gt;',['../structvcg_1_1face_1_1CurvatureDirBaseType.html',1,'vcg::face']]],
  ['curvaturedird_23',['CurvatureDird',['../classvcg_1_1face_1_1CurvatureDird.html',1,'vcg::face::CurvatureDird&lt; T &gt;'],['../classvcg_1_1vertex_1_1CurvatureDird.html',1,'vcg::vertex::CurvatureDird&lt; T &gt;']]],
  ['curvaturedirf_24',['CurvatureDirf',['../classvcg_1_1face_1_1CurvatureDirf.html',1,'vcg::face::CurvatureDirf&lt; T &gt;'],['../classvcg_1_1vertex_1_1CurvatureDirf.html',1,'vcg::vertex::CurvatureDirf&lt; T &gt;']]]
];
