######################################################################
# Automatically generated by qmake (2.00a) ven 24. giu 14:14:20 2005
######################################################################

TARGET = trimesh_hole
LIBPATH += 
DEPENDPATH += . 
INCLUDEPATH += . ../../..
CONFIG += console stl
TEMPLATE = app
SOURCES += trimesh_hole.cpp ../../../wrap/ply/plylib.cpp
HEADERS += ../../../wrap/ply/plylib.h