######################################################################
# Automatically generated by qmake (2.00a) ven 24. giu 14:14:20 2005
######################################################################

TEMPLATE      = subdirs
SUBDIRS       = trimesh_base \
                trimesh_topology\
                trimesh_smooth \
                trimesh_refine \
                trimesh_isosurface \
                trimesh_SDL

sources.files = *.pro
sources.path = .
INSTALLS += sources
